[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "BN128 precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-bn128"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.2.0"


[dependencies]
# crates
bn     = { package = "substrate-bn", version = "0.5", default-features = false }
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm    = { version = "0.25.0", default-features = false, features = ["with-codec"] }
# substrate
sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-io   = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"dp-evm/std",
	"evm/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
