[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "MODEXP precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-modexp"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.1.0"


[dependencies]
# crates
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm    = { version = "0.24.0", default-features = false, features = ["with-codec"] }
num    = { version = "0.3", default-features = false, features = ["alloc"] }
# substrate
sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-io   = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }

[dev-dependencies]
hex = "0.4.0"

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"dp-evm/std",
	"evm/std",
	"num/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
