[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "DISPATCH precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-dispatch"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.2.0"


[dependencies]
# crates
codec        = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
hyperspace-evm = { default-features = false, path = "../../../../evm" }
dp-evm       = { default-features = false, path = "../../../../../primitives/evm" }
evm          = { version = "0.25.0", default-features = false, features = ["with-codec"] }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-core       = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-io         = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"codec/std",
	"hyperspace-evm/std",
	"dp-evm/std",
	"evm/std",
]

substrate-std = [
	"frame-support/std",
	"sp-core/std",
	"sp-io/std",
]
